[smtp_config]
server = "smtp.prod.com"
port = 465
username = "${SMTP_USERNAME}"
password = "${SMTP_PASSWORD}"
encryption = "tls"

[imap_config]
server = "imap.production-server.com"
port = 993
username = "${IMAP_USERNAME}"
password = "${IMAP_PASSWORD}"
out_dir = "/var/data/prod/out"

[stu_config]
list = [
    { name = "测试学生1", email = "test1@example.com" },
    { name = "测试学生2", email = "test2@example.com" }
]

[log_config]
level = "info"
console_output = false
